### ISSUE TITLE
Regex fullsail(.com|.edu)

### ISSUE THREAD

**Issue by reactivepixel** [reactivepixel/Max-Bot#22]
Figure out how to regex, in node, to verify fullsail.com or fullsail.edu are within a supplied string.

For this, you should create a local branch and a new file to play within, but this will not be merged into the main codebase. Simply add a comment with the correct code in here surrounded by 3 backticks to make a code block.

```
const like = "so";
```

**Comment by carlosjunod** [comment]
This function is taking a string as a parameter and returning true or false according the result 

```
function validateFullSailEmail(string){
  let valid = false
  var email = string.search(/^[^-\s][a-zA-Z0-9_\-.#:]+@fullsail.?(com|edu)$(.*)/g)
  email != -1 ? valid = true : null
  return valid
}
```
try it in [codepen](https://codepen.io/carlosjunod/pen/ZXObQW?editors=0012)

**Comment by reactivepixel** [comment]
This looks like something that we could reuse in various spots, can you make this a module and start a ./lib folder for tools like this to exist within?

**Comment by carlosjunod** [comment]
.lib/emailValidation.js was created and added to a new branch called ```lib/emailValidation```

**Comment by reactivepixel** [comment]
@carlosjunod make a pull request to get it into Dev as per the DWA Branch model and this issue will be closed when that is accepted.
