### ISSUE TITLE
Generate a UUID (uuid4)

### ISSUE THREAD

**Issue by reactivepixel** [reactivepixel/Max-Bot#23]
Use the npm package [uuid](https://www.npmjs.com/package/uuid) to generate a UUID.

> Post your findings of how to properly use this package in the issue, do not merge any prototyping or practice code into the codebase.

**Comment by BHess2653** [comment]
I can look into this.

**Comment by carlosjunod** [comment]
In order to generate UUID we are going to use uuid package.
*this is the most basic usage of this pluging*

### Step 1: install npm package
install package using:
```npm install --save uuid```

### Step 2: Require package
``` const uuidv4 = require('uuid/v4') ```

### Step 3: Generate a uuid (and store it in a variable)
```const uuid = uuidv4()```

**Comment by reactivepixel** [comment]
Looks good!
