### ISSUE TITLE
Express Server Sibling Process

### ISSUE THREAD

**Issue by reactivepixel** [reactivepixel/Max-Bot#27]
Create another service within the codebase adjacent to the bot folder called *web* that houses a simple express web server that serves the necessary welcome, success, and failure pages as required for the Links to function in the emails.

> Note: This is not creating the full functionality of manipulating the DB or adding the Crew role, you are just making the 3 html pages.

**Comment by reactivepixel** [comment]
This will require an additional service added to PM2

**Comment by mykahT18** [comment]
@reactivepixel does the html pages need to have anything on them? Other than Welcome, Error, and Success for each different page.

**Comment by mykahT18** [comment]
@reactivepixel does the html pages need to have anything on them? Other than Welcome, Error, and Success for each different page.

**Comment by reactivepixel** [comment]
@mykahT18 Sorry for my delay, I don't have my github notifications configured well.

Simple Welcome Error and Success are perfect for now so long as the Welcome accepts a UUID parameter.

**Comment by mykahT18** [comment]
Okay, sounds good!

**Comment by mykahT18** [comment]
I have created the express server. The three pages are made and ready to go. The welcome route takes in the UUID code. Here are all the routes available: 
```
/welcome/:code
/error
/success
```
