### ISSUE TITLE
New Game Inclusion Request Mechanism

### ISSUE THREAD

**Issue by reactivepixel** [reactivepixel/Max-Bot#4]
~~Some mechanism that allows votes to be asynchronously cast for the inclusion of a new game under the Armada Flag. Once some a certain threshold is hit, officers are notified, or they can pull a report on open voting to see what direction community wants to go so they can have informed conversations / coordination for support and provide valuable and timely feedback to the community as a whole.~~

**Comment by reactivepixel** [comment]
Automate the inclusion of a new game.

* Add a new role to the list of game roles
* Create a Text and Voice channel for the new game
* Apply a standard set of configuration rules to the new channels
* Make an Automated announcement to the "Announcements" channel unveiling the game's inclusion in Armada (Create hook to trigger event)

**Comment by BHess2653** [comment]
Automate the inclusion of a new game.

- Add a new role to the list of game roles ✔︎
- Create a Text and Voice channel for the new game ✔︎
- Apply a standard set of configuration rules to the new channels ✔︎
- Make an Automated announcement to the "Announcements" channel unveiling the game's inclusion in Armada (Create hook to trigger event) ✘

**Comment by BHess2653** [comment]
The Automated announcement was the only part I did not get working yet. If anyone wants to review this or try adding the announcement at #153
