### ISSUE TITLE
Linting 

### ISSUE THREAD

**Issue by mykahT18** [reactivepixel/Max-Bot#42]
I think a great improvement would be changing the eslint to lint outside of the bot folder. So that all the code in the codebase will be up to Airbnb standards.

**Comment by BHess2653** [comment]
I've made a few updates to the linter but theres still some left that needs to be finished in the eslint branch.

**Comment by BHess2653** [comment]
Ok  I've updated the eslint in my branch eslint it still requires some final fixes.
