### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by mykahT18** [reactivepixel/Max-Bot#47]
I think for new people coming on  the project, it would be a good idea to have more comments. This will make it easier for them to have it right there in the code so they can see what is going on. Maybe a detailed sentence or two, especially on the parts where it is confusing. For example on the root.js and client.js files in the bot folder. Having a block comment at the top of the files explaining whats going on. It is just a suggestion 😸.

**Comment by reactivepixel** [comment]
I agree with the sentiment, but would have rather seen a direct reference to specific lines of code. 

Issue will not be addressed, too vague.
