### ISSUE TITLE
!Verify Trigger

### ISSUE THREAD

**Issue by reactivepixel** [reactivepixel/Max-Bot#65]

**Comment by ghost** [comment]
# !verify Trigger Recommendations

## Code Gen
I've locally added the randomstring package via npm (is working well), other code was clashing in a few environments.

## !verify via Direct Message
Would suggest looking into allowing the ```!verify``` command to be the only thing entered that then fires off a PM/DM from Max-Bot for sensitive information such as email address.
This will also ensure server channels don't get spammed (win win).

## feedback for users
Would suggest looking into giving feedback to user if the code entered was wrong and only allowing 3 attempts before flagging an officer for manual approval vs. waiting for time to expire.
