### ISSUE TITLE
move verify into DM

### ISSUE THREAD

**Issue by ghost** [reactivepixel/Max-Bot#83]
#### !verify should be sent in channel

* Then Max-Bot should carry the rest of the verify process into a Direct Message.

**Comment by LevanceWam** [comment]
I will tackle this issue

**Comment by reactivepixel** [comment]
Currently the Verify command exchange occurs within a public channel, the back and forth nature of that conversation would be better as a DM. This feature enhancement would allow for the initiation of the !verify within a discord server's channel but then move the conversation to a series of DMs as to not pollute the overall conversation of a channel.
