### ISSUE TITLE
Feedback on false input (code validation)

### ISSUE THREAD

**Issue by ghost** [reactivepixel/Max-Bot#84]
### Feedback on false input (code validation)

When user attempts to submit verification code that was generated and sent via email, the user has a set amount of time to submit that code. If user submits the wrong code nothing happen, only when either the correct code is entered will it prompt or when time expires and the bot conversation has not been satisfied with the successful code generated.

#### would like to give user 3 attempts then expire timer if possible.

* may need new collector method for this

**Comment by reactivepixel** [comment]
Not relevant, closing.
